server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/${KC_REALM}
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/${KC_REALM}